version: '3'

services:
  postgres:
    container_name: tws
    image: postgres:latest
    environment:
      POSTGRES_USER: "tws"
      POSTGRES_PASSWORD: "tws"
      POSTGRES_DB: "postgres"
    ports:
      - "54322:5432"
