
package ru.mxmztsv.app.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ru.mxmztsv.app.ClientSearchResponseType;
import ru.mxmztsv.app.model.ClientRequest;
import ru.mxmztsv.app.model.ClientResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientServiceImpl", targetNamespace = "http://soap.app.mxmztsv.ru/")
@XmlSeeAlso({
    ru.mxmztsv.app.ObjectFactory.class,
    ru.mxmztsv.app.model.ObjectFactory.class,
    ru.mxmztsv.app.soap.ObjectFactory.class
})
public interface ClientServiceImpl {


    /**
     * 
     * @param request
     * @param id
     * @return
     *     returns ru.mxmztsv.app.model.ClientResponse
     * @throws ClientServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientResponse", targetNamespace = "http://app.mxmztsv.ru/")
    @RequestWrapper(localName = "update", targetNamespace = "http://soap.app.mxmztsv.ru/", className = "ru.mxmztsv.app.soap.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://soap.app.mxmztsv.ru/", className = "ru.mxmztsv.app.soap.UpdateResponse")
    @Action(input = "http://soap.app.mxmztsv.ru/ClientServiceImpl/updateRequest", output = "http://soap.app.mxmztsv.ru/ClientServiceImpl/updateResponse", fault = {
        @FaultAction(className = ClientServiceException_Exception.class, value = "http://soap.app.mxmztsv.ru/ClientServiceImpl/update/Fault/ClientServiceException")
    })
    public ClientResponse update(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "request", targetNamespace = "")
        ClientRequest request)
        throws ClientServiceException_Exception
    ;

    /**
     * 
     * @param id
     * @throws ClientServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://soap.app.mxmztsv.ru/", className = "ru.mxmztsv.app.soap.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://soap.app.mxmztsv.ru/", className = "ru.mxmztsv.app.soap.DeleteResponse")
    @Action(input = "http://soap.app.mxmztsv.ru/ClientServiceImpl/deleteRequest", output = "http://soap.app.mxmztsv.ru/ClientServiceImpl/deleteResponse", fault = {
        @FaultAction(className = ClientServiceException_Exception.class, value = "http://soap.app.mxmztsv.ru/ClientServiceImpl/delete/Fault/ClientServiceException")
    })
    public void delete(
        @WebParam(name = "id", targetNamespace = "")
        Long id)
        throws ClientServiceException_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns ru.mxmztsv.app.model.ClientResponse
     * @throws ClientServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientResponse", targetNamespace = "http://app.mxmztsv.ru/")
    @RequestWrapper(localName = "create", targetNamespace = "http://soap.app.mxmztsv.ru/", className = "ru.mxmztsv.app.soap.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://soap.app.mxmztsv.ru/", className = "ru.mxmztsv.app.soap.CreateResponse")
    @Action(input = "http://soap.app.mxmztsv.ru/ClientServiceImpl/createRequest", output = "http://soap.app.mxmztsv.ru/ClientServiceImpl/createResponse", fault = {
        @FaultAction(className = ClientServiceException_Exception.class, value = "http://soap.app.mxmztsv.ru/ClientServiceImpl/create/Fault/ClientServiceException")
    })
    public ClientResponse create(
        @WebParam(name = "request", targetNamespace = "")
        ClientRequest request)
        throws ClientServiceException_Exception
    ;

    /**
     * 
     * @param firstName
     * @param lastName
     * @param data
     * @param category
     * @param status
     * @return
     *     returns ru.mxmztsv.app.ClientSearchResponseType
     * @throws ClientServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientSearchResponse", targetNamespace = "http://app.mxmztsv.ru/")
    @RequestWrapper(localName = "searchClients", targetNamespace = "http://soap.app.mxmztsv.ru/", className = "ru.mxmztsv.app.soap.SearchClients")
    @ResponseWrapper(localName = "searchClientsResponse", targetNamespace = "http://soap.app.mxmztsv.ru/", className = "ru.mxmztsv.app.soap.SearchClientsResponse")
    @Action(input = "http://soap.app.mxmztsv.ru/ClientServiceImpl/searchClientsRequest", output = "http://soap.app.mxmztsv.ru/ClientServiceImpl/searchClientsResponse", fault = {
        @FaultAction(className = ClientServiceException_Exception.class, value = "http://soap.app.mxmztsv.ru/ClientServiceImpl/searchClients/Fault/ClientServiceException")
    })
    public ClientSearchResponseType searchClients(
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "status", targetNamespace = "")
        Status status,
        @WebParam(name = "category", targetNamespace = "")
        Category category,
        @WebParam(name = "data", targetNamespace = "")
        String data)
        throws ClientServiceException_Exception
    ;

}
